<?php
if(!defined('IN_GAME')) exit('Access Denied');
$npcinit = array
	(
		'name' => '',	'pass' => 'bra', 'gd' => 'm',	'icon' => 0,	'club' => 0,	
		'mhp' => 0,	'msp' => 0,	'att' => 0,	'def' => 0,	'pls' => 0,	'lvl' => 0,
		'money' => 0,	'inf' => '',	'rage' => 0,	'pose' => 0,	'tactic' => 0,	
		'killnum' => 0,	'state' => 1,	'teamID' => '',	'teamPass' => '','bid' => 0,
		'wep' => '',	'wepk' => '',	'wepe' => 0,	'weps' => 0,	'wepsk' => '',
		'arb' => '',	'arbk' => '',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
		'arh' => '',	'arhk' => '',	'arhe' => 0,	'arhs' => 0,	'arhsk' => '',
		'arf' => '',	'arfk' => '',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
		'ara' => '',	'arak' => '',	'arae' => 0,	'aras' => 0,	'arask' => '',
		'art' => '',	'artk' => '',	'arte' => 0,	'arts' => 0,	'artsk' => '',
		'itm0' => '',	'itmk0' => '',	'itme0' => 0,	'itms0' => 0,	'itmsk0' => '',
		'itm1' => '',	'itmk1' => '',	'itme1' => 0,	'itms1' => 0,	'itmsk1' => '',
		'itm2' => '',	'itmk2' => '',	'itme2' => 0,	'itms2' => 0,	'itmsk2' => '',
		'itm3' => '',	'itmk3' => '',	'itme3' => 0,	'itms3' => 0,	'itmsk3' => '',
		'itm4' => '',	'itmk4' => '',	'itme4' => 0,	'itms4' => 0,	'itmsk4' => '',
		'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
		'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
		'gemname' => '','gemstate' => 0,'gempower' => 0,'gemlvl' => 0,	'gemexp' => '',		
	);
$npcinfo = array
	( 
	1 => array
		(
		'mode' => 1,
		'num' => 1,
		'pass' => 'bra',
		'club' => 0,
		//'skills' => 22966,	//14号技能和5号技能
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'm',
		'pls' => 0,
		'mhp' => 7500,
		'msp' => 4000,
		'att' => 750,
		'def' => 750,
		'lvl' => 75,
		'skill' => 444,
		'money' => 9999,
		'arb' => '特种部队迷彩服',
		'arbk' => 'DB',	'arbe' => 3000,	'arbs' => 3000,	'arbsk' => 'Ab',
		'arh' => '源氏之盔',
		'arhk' => 'DH',	'arhe' => 1444,	'arhs' => 3000,
		'arf' => 'Nike的Air Force1',
		'arfk' => 'DF',	'arfe' => 1444,	'arfs' => 3000,
		'ara' => '米奇的手袋',
		'arak' => 'DA',	'arae' => 1444,	'aras' => 3000,	'arask' => '',
		'art' => '龙虎旗帜',
		'artk' => 'A',	'arte' => 1000,	'arts' => 1000,	'artsk' => 'H',
		'sub' => array
		(
			0 => array
			(
			'name' => '坂持 金发',
			'icon' => 42,
			'wep' => '水素粒子水铁炮',
			'wepk' => 'WG',	'wepe' => 1280,	'weps' => 9999,	'wepsk' => 'rfn',
			'itm1' => '游戏解除钥匙',
			'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 1,
			//'itm2' => '黑色碎片',
			//'itmk2' => 'Y',	'itme2' => 1,	'itms2' => 1,
			//'itm3' => '不要按这个按钮！',
			//'itmk3' => 'Y',	'itme3' => 1,	'itms3' => 1,
			),
		),
	),
	2 => array
		(
		'mode' => 1,
		'num' => 4,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'gd' => 'm',
		'teamID' => '',
		'teamPass' => '',
		'pls' => 0,
		'mhp' => 3000,
		'msp' => 200,
		'att' => 250,
		'def' => 350,
		'lvl' => 30,
		'skill' => 135,
		'money' => 1600,
		'arb' => '军服α',
		'arbk' => 'DB',	'arbe' => 800,	'arbs' => 100,
		'arh' => '军帽α',
		'arhk' => 'DH',	'arhe' => 800,	'arhs' => 100,
		'arf' => '军靴α',
		'arfk' => 'DF',	'arfe' => 800,	'arfs' => 800,
		'ara' => '军用手套α',
		'arak' => 'DA',	'arae' => 800,	'aras' => 800,
		//'itm5' => '好人卡',
		//'itmk5' => 'Y',
		//'itme5' => 1,
		//'itms5' => 16,
		'sub' => array
			(
			0 => array
			(
			'name' => '甲斐 山诚',
			'icon' => 0,
			'wep' => '个人定制式乌兹冲锋枪',
			'wepk' => 'WG',
			'wepe' => 120,
			'weps' => 200,
			'wepsk' => 'NnrtZ',
			'club' => 4,
			'skill' => 300,
			'att' => 300,
			'arb' => '强化作战服D',
			'arbk' => 'DB',	'arbe' => 800,	'arbs' => 600,	'arbsk' => 'aGKU',
			'arh' => '强化作战服H',
			'arhk' => 'DH',	'arhe' => 800,	'arhs' => 600,	'arhsk' => 'WZ',
			'arf' => '强化作战服F',
			'arfk' => 'DF',	'arfe' => 800,	'arfs' => 600,	'arfsk' => 'mZ',
			'ara' => '强化作战服A',
			'arak' => 'DA',	'arae' => 800,	'aras' => 600,	'arask' => 'Z',
			'art' => '妻子的近照',
			'artk' => 'A',	'arte' =>10 ,	'arts' =>25 ,	'artsk' => 'AH',
			'itm1' => '军部配给的压缩饼干',
			'itmk1' => 'HS',	'itme1' => 2000,	'itms1' => 30,
			'itm2' => '加强型军用匕首',
			'itmk2' => 'WK',	'itme2' => 175,	'itms2' => 60,	'itmsk2' => 'LN',
			'itm3' => '紧急情况指示器',
			'itmk3' => 'Y',	'itme3' => 1,	'itms3' => 1,
			),
			1 => array
			(
			'name' => '條原 乙妃',
			'icon' => 0,
			'wep' => '试验型构成破坏枪',
			'wepk' => 'WG',
			'wepe' => 10,
			'weps' => 200,
			'wepsk' => 'eLr',
			'club' => 0,
			'rage' => 0,
			'pose'=> 4,
			'tactic' => 4,
			'gd' => 'f',
			'mhp' => 4500,
			'msp' => 200,
			'att' => 100,
			'def' => 800,
			'lvl' => 30,
			'skill' => 150,
			'money' => 2000,
			'arb' => '缀满没用花边的防护服',
			'arbk' => 'DB',	'arbe' => 800,	'arbs' => 100,	'arbsk' => 'GKFIZ',
			'arh' => '头戴式透镜',
			'arhk' => 'DH',	'arhe' => 800,	'arhs' => 100,	'arhsk' => 'WM',
			'arf' => '厚底靴',
			'arfk' => 'DF',	'arfe' => 300,	'arfs' => 500,	'arfsk' => 'ES',
			'ara' => '试验型隔断力场',
			'arak' => 'DA',	'arae' => 800,	'aras' => 5,	'arask' => 'AB',
			'art' => '随身实验笔记',
			'artk' => 'A',	'arte' => 50,	'arts' => 30,	'artsk' => 'H',
			'itm1' => '试验型灵子发生装置',
			'itmk1' => 'WF',	'itme1' => 5,	'itms1' => 200,	'itmsk1' => 'w',
			'itm2' => '军部配给的薄荷糖',
			'itmk2' => 'HS',	'itme2' => '1000',	'itms2' => '15',
			'itm3' => '觉醒剂试制二型',
			'itmk3' => 'Y',	'itme3' => '1',	'itms3' => '1',
			),
			2 => array
			(
			'name' => '三叶 幸',
			'icon' => 0,
			'wep' => '祭神之镜',
			'wepk' => 'WF',
			'wepe' => 180,
			'weps' => 200,
			'wepsk' => 'Nwrt',
			'club' => 98,
			'rage' => 0,
			'pose'=> 0,
			'tactic' => 3,
			'gd' => 'f',
			'pls' => 24,
			'mhp' => 3500,
			'msp' => 200,
			'att' => 450,
			'def' => 600,
			'lvl' => 35,
			'skill' => 200,
			'money' => 1600,
			'arb' => '祭仪巫女服',
			'arbk' => 'DB',	'arbe' => 600,	'arbs' => 150,	'arbsk' => 'aI',
			'arh' => '白诘草头饰',
			'arhk' => 'DH',	'arhe' => 800,	'arhs' => 100,
			'arf' => '结实的木屐',
			'arfk' => 'DF',	'arfe' => 300,	'arfs' => 500,	'arfsk' => 'E',
			'ara' => '祭仪的护袖',
			'arak' => 'DA',	'arae' => 500,	'aras' => 500,	'arask' => 'c',
			'art' => '白诘草神社主持之印',
			'artk' => 'A',	'arte' => 50,	'arts' => 50,	'artsk' => 'Ht',
			'itm1' => '护身咒弩',
			'itmk1' => 'WG',	'itme1' => 500,	'itms1' => 5,	'itmsk1' => 'dLo',
			'itm2' => '收不到信号的对讲机',
			'itmk2' => 'Y',	'itme2' => '1',	'itms2' => '1',
			),
			3 => array
			(
			'name' => '无聊',
			'icon' => 224,
			'att' => 300,
			'money' => 2500,
			'wep' => '46cm三连装单兵手持炮',
			'wepk' => 'WJ',	'wepe' => 175,	'weps' => 200,	'wepsk' => 'cNrZ',
			'arb' => '仿生舰装-零式',
			'arbk' => 'DB',	'arbe' => 800,	'arbs' => 100,	'arbsk' => 'aU',
			'arh' => '海军军帽',
			'arhk' => 'DH',	'arhe' => 800,	'arhs' => 100,	'arhsk' => 'WZ',
			'arf' => '海军军靴',
			'arfk' => 'DF',	'arfe' => 800,	'arfs' => 800,	'arfsk' => 'Z',
			'ara' => '捂脸用动力手套',
			'arak' => 'DA',	'arae' => 800,	'aras' => 800,	'arask' => 'Z',
			'art' => '萝莉信仰',
			'artk' => 'A',	'arte' =>10 ,	'arts' =>25 ,	'artsk' => 'HZ',
			'itm1' => '整锅野炊',
			'itmk1' => 'HS',	'itme1' => 500,	'itms1' => 1,
			'itm2' => '作礼物用的棒棒糖',
			'itmk2' => 'HB',	'itme2' => 30,	'itms2' => 60,
			'itm3' => '【GOLD RUSH ELITE】',
			'itmk3' => 'm',	'itme3' => 100,	'itms3' => 1,
			'itm4' => '锅',
			'itmk4' => 'DB',	'itme4' => 500,	'itms4' => 100,	'itmsk4' => 'GK',
			),
		),
	),
	
	//3原本是杂兵位置，现在移到90
	//女主系列在本版本2.99SP3中下线，此位置留给星球意识。

	11 => array
		(
		'mode' => 2,
		'num' => 2,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'gd' => 'f',
		'teamID' => '',
		'teamPass' => '',
		'pls' => 8,
		'mhp' => 3000,
		'msp' => 400,
		'att' => 2000,
		'def' => 4000,
		'lvl' => 75,
		'skill' => 800,
		'money' => 40000,
		'arb' => '武装巫女服',
		'arbk' => 'DB',	'arbe' => 3000,	'arbs' => 300,	'arbsk' => 'AIZ',
		'arh' => '白诘草发髻',
		'arhk' => 'DH',	'arhe' => 2000,	'arhs' => 300,	'arhsk' => 'bWZ',
		'arf' => '良木制木屐',
		'arfk' => 'DF',	'arfe' => 2000,	'arfs' => 300,	'arfsk' => 'SZ',
		'ara' => '巫女护袖',
		'arak' => 'DA',	'arae' => 2000,	'aras' => 300,	'arask' => 'MmZ',
		'art' => '白诘草护符',
		'artk' => 'A',	'arte' => 800,	'arts' => 800,	'artsk' => 'Hv',
		//'itm5' => '好人卡',
		//'itmk5' => 'Y',
		//'itme5' => 1,
		//'itms5' => 16,
		'sub' => array
			(
			0 => array
			  (
			'name' => '神鸣阳香',
			'icon' => 220,
			'wep' => '双枪-黄金猎犬',
			'wepk' => 'WG',
			'wepe' => 500,
			'weps' => 400,
			'wepsk' => 'dfrNO|',//爆炸+灼焰+连击+冲击+进化+成长
			),
			1 => array
			(
			'name' => '神鸣此月',
			'icon' => 221,
			'wep' => '太刀-月下美人',
			'wepk' => 'WK',
			'wepe' => 625,
			'weps' => 400,
			'wepsk' => 'Lk=NO|',//致残+冰华+吸血+冲击+进化+成长
			),
		),
	),
	12 => array
		(
		'mode' => 1,//上级小兵的基准，深渊众
		'num' => 28,
		'pass' => 'bra',
		'icon' => 0,
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'pls' => 22,
		'mhp' => 2000,
		'msp' => 200,
		'att' => 225,
		'def' => 350,
		'lvl' => 25,
		'skill' => 135,
		'money' => 1600,
		'icon' => 0,
		//'arb' => '普通的制服',
		//'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
		//'arh' => '普通的帽子',
		//'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
		//'arf' => '普通的鞋子',
		//'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
		//'ara' => '普通的手套',
		//'arak' => 'DA',	'arae' => 75,	'aras' => 100,
		'sub' => array
		(
			0 => array
			(
			'name' => '那回早栗',
			'icon' => 0,
			'gd' => 'f',
			'wep' => '影人加护的发夹',
			'wepk' => 'WCF',
			'wepe' => 66,
			'weps' => '∞',
			'arb' => '学生制服',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arf' => '学生便鞋',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'itm1' => '恶魔晶状体',
			'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 5,	//'itmsk1' => 'id',
			'itm2' => '集换卡片-那回早栗',
			'itmk2' => 'WC',	'itme2' => 150,	'itms2' => 15,	'itmsk2' => 'r',
			),
			1 => array
			(
			'name' => 'Lugia',
			'icon' => 0,
			'gd' => 'm',
			'wep' => '手办展示柜的超重锁头',
			'wepk' => 'WP',	'wepe' => 80,	'weps' => '150',	'wepsk' => 'c',
			'arb' => '学生制服',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arf' => '学生便鞋',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'itm1' => '恶魔晶状体',
			'itmk1' => 'X',	'itme1' => 1,	'itms1' => 1,
			//'itmsk1' => 'id',
			'itm2' => '集换卡片-Lugia',
			'itmk2' => 'WC',	'itme2' => 110,	'itms2' => 10,	'itmsk2' => 'N',
			'itm3' => '少女的经血',
			'itmk3' => 'PH',	'itme3' => 750,	'itms3' => 1,
			),
			2 => array
			(
			'name' => 'arkpanda',
			'gd' => 'r',//
			'icon' => 0,
			'money' => 666,
			'wep' => '新鲜笋竹',
			'wepk' => 'WG',	'wepe' => 200,	'weps' => 1,	'wepsk' => 'o',
			'itm1' => '剥皮竹笋',
			'itmk1' => 'HH',	'itme1' => 200,	'itms1' => 1,	'itmsk1' => '',
			'itm2' => '笋干',
			'itmk2' => 'HS',	'itme2' => 200,	'itms2' => 5,	'itmsk2' => '',
			'itm3' => '集换卡片-arkpanda',
			'itmk3' => 'WC',	'itme3' => 40,	'itms3' => 300,	'itmsk3' => '',
			),
			3 => array
			(
			'name' => 'Ground0',
			'icon' => 0,
			'gd' => 'm',
			'wep' => '什么问题都能解决的C4炸弹',
			'wepk' => 'WD',	'wepe' => 275,	'weps' => '150',	'wepsk' => 'dNw',//爆炸+冲击+音波
			'arb' => '厚重防护服B',
			'arbk' => 'DB',	'arbe' => 200,	'arbs' => 100,	'arbsk' => 'DUZ',
			'arh' => '厚重防护服H',
			'arhk' => 'DH',	'arhe' => 100,	'arhs' => 100,	'arhsk' => 'DUW',
			'arf' => '厚重防护服F',
			'arfk' => 'DF',	'arfe' => 100,	'arfs' => 100,	'arfsk' => 'DU',
			'ara' => '厚重防护服A',
			'arak' => 'DA',	'arae' => 100,	'aras' => 100,	'arask' => 'DU',
			'itm2' => '《爆系指南》',
			'itmk2' => 'VD',	'itme2' => 25,	'itms2' => 3,	'itmsk2' => '',
			'itm3' => '集换卡片-Ground0',
			'itmk3' => 'WC',	'itme3' => 800,	'itms3' => 5,	'itmsk3' => 'dNwu',//爆炸+冲击+音波+火焰
			),
			4 => array
			(
			'name' => '无脸咸鱼偶像宅',
			'icon' => 0,
			'gd' => 'm',
			'wep' => '人生20余年唯一的女朋友',
			'wepk' => 'WN',	'wepe' => 80,	'weps' => '150',	'wepsk' => 'v',
			'arb' => '发黄的格子衬衫',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arh' => '“爱酱大☆胜☆利”偶像应援头巾',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'arf' => '很久没洗的阿迪王',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'ara' => '擦汗用的毛巾',
			'arak' => 'DA',	'arae' => 75,	'aras' => 100,
			),
			5 => array
			(
			'name' => '剧毒的lz1',
			'gd' => 'r',//
			'icon' => 0,
			'wep' => '暗之道化师',
			'wepk' => 'WC',	'wepe' => 1,	'weps' => 191,	'wepsk' => 'p',
			'arb' => '节操',
			'arbk' => 'DB',	'arbe' => 120,	'arbs' => 5,	'arbsk' => '',
			'arh' => '节操',
			'arhk' => 'DH',	'arhe' => 120,	'arhs' => 5,	'arhsk' => '',
			'arf' => '节操',
			'arfk' => 'DF',	'arfe' => 120,	'arfs' => 5,	'arfsk' => '',
			'ara' => '节操',
			'arak' => 'DA',	'arae' => 120,	'aras' => 5,	'arask' => '',
			'art' => '节操',
			'artk' => 'A',	'arte' => 120,	'arts' => 5,	'artsk' => '',
			'itm1' => '大夭使的气息',
			'itmk1' => 'PB',	'itme1' => 10000,	'itms1' => 2,	'itmsk1' => '',
			'itm2' => '大天使的气息',
			'itmk2' => 'HB',	'itme2' => 10000,	'itms2' => 2,	'itmsk2' => '',
			'itm3' => '像围棋子一样的饼干',
			'itmk3' => 'HB',	'itme3' => 9999,	'itms3' => 1,	'itmsk3' => '',
			'itm4' => '毒药',
			'itmk3' => 'Y',	'itme4' => 1,	'itms4' => 33,	'itmsk4' => '',
			'itm5' => '紧急体力强化剂z',
			'itmk5' => 'HB',	'itme5' => 4000,	'itms5' => 5,	'itmsk5' => '',
			),
			6 => array
			(
			'name' => 'flyair234',
			'gd' => 'f',//
			'icon' => 0,
			'wep' => '特大号振动棒',
			'wepk' => 'WP',	'wepe' => 35,	'weps' => 50,
			'arh' => '破旧的皮项圈',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'arf' => '写满正字的丝袜',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'money' => 200,
			'itm1' => '电脑配件',
			'itmk1' => 'HH',	'itme1' => 160,	'itms1' => 2,	'itmsk1' => '',
			),
			7 => array
			(
			'name' => '约翰蛤利.A',
			'gd' => 'm',//
			'icon' => 0,
			'pose' => 4,
			'tactic' => 3,
			'money' => 400,
			'wep' => '可拆卸狙击步枪',
			'wepk' => 'WG',	'wepe' => 80,	'weps' => 6,	'wepsk' => '',
			'arb' => '白色制服',
			'arbk' => 'DB',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
			'arf' => '皮鞋',
			'arfk' => 'DF',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
			'itm1' => '子弹',
			'itmk1' => 'GB',	'itme1' => 1,	'itms1' => 12,	'itmsk1' => '',
			),
			8 => array
			(
			'name' => 'sandeflee',
			'gd' => 'm',//
			'icon' => 0,
			'wep' => '诺基亚',	'wepk' => 'WP',
			'arb' => '洗得发白的衣服',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arh' => '破旧的眼镜',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'arf' => '耐用的鞋子',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'ara' => '画上的手表',
			'arak' => 'DA',	'arae' => 0,	'aras' => '∞',	'arask' => 'v',
			'itm1' => '可乐',
			'itmk1' => 'HS',	'itme1' => 100,	'itms1' => 1,	'itmsk1' => '',
			'itm2' => '眼药水',
			'itmk2' => 'PH',	'itme2' => 1,	'itms2' => 1,	'itmsk2' => '',
			),
			9 => array
			(
			'name' => '幽灵轻3',
			'gd' => 'm',//
			'icon' => 0,
			'pls' => 13,
			'pose' => 4,
			'tactic' => 2,
			'def' => 500,//被要求防御力高一些
			'wep' => '被无视的怨念',
			'wepk' => 'WF',	'wepe' => 25,	'wepsk' => 't=',
			'arb' => '幽灵的身体',
			'arbk' => 'DB', 'arbe' => 80,	'arbsk'=>'PKGC',
			'arh' => '超高度近视眼镜',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'ara' => '存在感提高护符',
			'arak' => 'DA',	'arae' => 75,	'aras' => 100,
			'art' => '彩虹小马全集',
			'artk' => 'A',	'arte' => 10,	'arts' => 10,
			'itm1' => '装有H173的注射器',
			'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 1,	'itmsk1' => '',
			'itm2' => '镇魂瞪眼',
			'itmk2' => 'WF',	'itme2' => 100,	'itms2' => '∞',	'itmsk2' => 'nrw',
			'itm3' => '卡牌-死灵之颜',
			'itmk3' => 'WC',	'itme3' => 170,	'itms3' => '∞',	'itmsk3' => 'e',
			),
			10 => array
			(
			'name' => 'Raven', 'gd' => 'm',	'icon' => 0,
			'pose' => 4,	'tactic' => 4,
			'wep' => 'ネビリム(弓)',
			'wepk' => 'WG',	'wepe' => 30,	'weps' => 45,	'wepsk' => 'rNp',
			'arb' => '特制的战斗服',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,	'arbsk' => 'v',
			'arh' => '束发带',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'arf' => '被封印的足护具',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,	'arfsk' => 'M',
			'ara' => '魔导器',
			'artk' => 'A',	'arte' => 10,	'arts' => 10,
			'art' => '莉斯莉特的项链',
			'artk' => 'A',	'arte' => 10,	'arts' => 10,
			),
			11 => array
			(
			'name' => 'deadhunk',
			'icon' => 0,
			'gd' => 'm',
			'wep' => '董存瑞双面胶炸药',
			'wepk' => 'WD',	'wepe' => 100, 'weps' => 25,
			'arb' => '厚实的迷彩衣',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arh' => '墨西哥眼镜蛇',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'arf' => '阿迪王',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'ara' => '劳力士',
			'arak' => 'DA',	'arae' => 75,	'aras' => 100,
			'art' => '那回早栗玩偶',
			'artk' => 'A',	'arte' => 10,	'arts' => 10,
			'itm1' => '大力水手菠菜',
			'itmk1' => 'HS',
			'itme1' => 150,	'itms1' => 5,	'itmsk1' => '',
			'itm2' => '拉登头套',
			'itmk2' => 'DH',
			'itme2' => 50,	'itms2' => 25,	'itmsk2' => '',
			),
			12 => array
			(
			'name' => '竹箭',
			'icon' => 0,
			'gd' => 'f',
			'pls' => 9,
			'arb' => '节操',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arh' => '节操',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'arf' => '节操',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'ara' => '节操',
			'arak' => 'DA',	'arae' => 75,	'aras' => 100,
			'itm1' => '奇异甜食',
			'itmk1' => 'ME',	'itme1' => 12,	'itms1' => 1,	'itmsk1' => '',
			'itm2' => '奇异甜食',
			'itmk2' => 'ME',	'itme2' => 12,	'itms2' => 1,	'itmsk2' => '',
			'itm3' => '奇异甜食',
			'itmk3' => 'ME',	'itme3' => 12,	'itms3' => 1,	'itmsk3' => '',
			'itm4' => '奇异甜食',
			'itmk4' => 'ME',	'itme4' => 12,	'itms4' => 1,	'itmsk4' => '',
			),
			13 => array
			(
			'name' => '瓦顿巴',
			'icon' => 0,
			'gd' => 'm',
			'money' => 100,
			'wep' => '造型残念的构成体铁棍',
			'wepk' => 'WP',	'wepe' => 60, 'weps' => 45,
			'arb' => '硅素标准战斗服-身',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arf' => '硅素标准战斗服-靴',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'ara' => '硅素标准战斗服-手',
			'arak' => 'DA',	'arae' => 75,	'aras' => 100,
			'itm1' => '便当',
			'itmk1' => 'HS',	'itme1' => 300,	'itms1' => 1,	'itmsk1' => '',
			),
			14 => array
			(
			'name' => '狂信者',
			'icon' => 0,
			'gd' => 'r',
			'wep' => '难以名状的长枪',
			'wepk' => 'WK',	'wepe' => 40,	'weps' => 5,	'wepsk' => 'n',
			'arb' => '仪式用长袍',
			'arbk' => 'DB',	'arbe' => 20,	'arbs' => 5,	'arbsk' => '',
			'arh' => '奇怪的面罩',
			'arhk' => 'DH',	'arhe' => 10,	'arhs' => 30,	'arhsk' => '',
			'ara' => '柔软的皮质护手',
			'arak' => 'DA',	'arae' => 10,	'aras' => 10,	'arask' => '',
			'art' => '邪神的护符',
			'artk' => 'A',	'arte' => 10,	'arts' => 5,	'artsk' => 'qV',
			'itm1' => '难以名状的肉块',
			'itmk1' => 'PH',	'itme1' => 40,	'itms1' => 2,	'itmsk1' => '',
			'itm2' => '血水',
			'itmk2' => 'PS',	'itme2' => 100,	'itms2' => 1,	'itmsk2' => '',
			),
			15 => array
			(
			'name' => 'WS创',
			'icon' => 1215,
			'gd' => 'm',
			'club' => 0,
			'mhp' => 2888,
			'att' => 88,
			'def' => 88,
			'lvl' => 30,
			'skill' => 100,
			'money' => 888,
			'rage' => 88,
			'pose' => 1,
			'tactic' => 3,
			'pls' => 99,
			'wep' => '非法枪械部件',
			'wepk' => 'WJ',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'upwoV',
			'arb' => '偷来的『传说中的银白裙』',
			'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'a',
			'arh' => '偷来的少女的高筒靴',
			'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'DF',
			'arf' => '偷来的☆黑丝☆',
			'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => 'ZH',
			'ara' => '偷来的露趾凉鞋',
			'arak' => 'DA',	'arae' => 888,	'aras' => 888,
			'art' => '别忘的讲义',
			'artk' => 'A',	'arte' => 888,	'arts' => 888,	'artsk' => 'cx',
			'itm1' => '☆黑丝☆',
			'itmk1' => 'PB',	'itme1' => 88,	'itms1' => '∞',	'itmsk1' => 'Z',
			),
			16 => array
			(
			'name' => '卖萌少女 团圆久子',
			'icon' => 1216,
			'pls' => 23,
			'gd' => 'f',
			'pose' => 0,
			'tactic' => 0,
			'club' => 99,
			'mhp' => 2800,
			'att' => 1,
			'def' => 75,
			'lvl' => 10,
			'skill' => 800,
			'money' => 3,
			'rage' => 5,
			'pose' => 2,
			'tactic' => 3,
			'wep' => '少女的手刀',
			'wepk' => 'WK',	'wepe' => 1,	'weps' => 1000,	'wepsk' => 'NnrL',
			'arb' => '蕾丝连衣裙',
			'arbk' => 'DB',	'arbe' => 600,	'arbs' => 100,
			'arh' => '单片眼镜',
			'arhk' => 'DH',	'arhe' => 600,	'arhs' => 100,
			'arf' => '过膝黑丝',
			'arfk' => 'DF',	'arfe' => 600,	'arfs' => 100,
			'ara' => '装饰物手镯',
			'arak' => 'DA',	'arae' => 600,	'aras' => 100,
			'art' => '黑科技',
			'artk' => 'A',	'arte' => 1,	'arts' => 1,	'artsk' => 'H',
			),
			17 =>array
			(
			'name' => '反枕酱',
			'icon' => 1217,
			'gd' => 'r',
			'club' => 0,
			'mhp' => 2888,
			'att' => 88,
			'def' => 88,
			'lvl' => 30,
			'skill' => 100,
			'money' => 888,
			'rage' => 88,
			'pose' => 1,
			'tactic' => 3,
			'pls' => 99,
			'wep' => '枣',
			'wepk' => 'WC',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'eipuw',
			'arb' => '白色的身躯',
			'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'a',
			'arh' => '白色的头部',
			'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'DF',
			'arf' => '白色的短足',
			'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => 'ZH',
			'ara' => '白色的短手',
			'arak' => 'DA',	'arae' => 888,	'aras' => 888,
			'art' => '阴影中的镰鼬酱',
			'artk' => 'A',	'arte' => 888,	'arts' => 888,	'artsk' => 'cx',
			'itm1' => '可以吃的枣',
			'itmk1' => 'HB',	'itme1' => 88,	'itms1' => '∞',	'itmsk1' => 'z',
			),
			18 => array
			(
			'name' => '鬼灯夕夜',
			'icon' => 0,
			'gd' => 'f',
			'mhp' => 1600,
			'att' => 70,
			'def' => 240,
			'money' => 1600,
			'pose' => 2,
			'tactic' => 3,
			'wep' => '沾血的小刀',
			'wepk' => 'WK',	'wepe' => 50,	'weps' => 9,	'wepsk' => 'iJL',
			'arb' => '某个奇怪的城堡里找到的女仆装',
			'arbk' => 'DB',	'arbe' => 10,	'arbs' => 9,	'arbsk' => 'ADK',
			'arh' => '和女仆装一起找到的猫耳',
			'arhk' => 'DH',	'arhe' => 10,	'arhs' => 9,	'arhsk' => '',
			'arf' => '白色过膝袜',
			'arfk' => 'DF',	'arfe' => 10,	'arfs' => 9,	'arfsk' => '',
			'ara' => '手链',
			'arak' => 'DA',	'arae' => 1,	'aras' => 1,	'arask' => '',
			'art' => '猫尾',
			'artk' => 'A',	'arte' => 10,	'arts' => 9,	'artsk' => 'uz',
			'itm1' => '学生证',
			'itmk1' => 'A',	'itme1' => 1,	'itms1' => 1,	'itmsk1' => 'E',
			),
			19 => array
			(
			'name' => '节操',
			'icon' => 0,
			'gd' => 'f',
			'wep' => '缀满用过的套套的御币',
			'wepk' => 'WP',	'wepe' => 80,	'weps' => '150',	'wepsk' => '',
			'arb' => '巫女服',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			),
			20 => array
			(
			'name' => '天纵',
			'icon' => 0,
			'gd' => 'm',
			'wep' => '齐物',
			'wepk' => 'WK',
			'wepe' => 80,
			'weps' => '150',
			'wepsk' => '',
			'arb' => '黑色风衣',
			'arbk' => 'DB',	'arbe' => 150,	'arbs' => 100,
			'arh' => '黑色兜帽',
			'arhk' => 'DH',	'arhe' => 75,	'arhs' => 100,
			'arf' => '黑色长靴',
			'arfk' => 'DF',	'arfe' => 75,	'arfs' => 100,
			'ara' => '黑色手套',
			'arak' => 'DA',	'arae' => 75,	'aras' => 100,
			'art' => '墨镜',
			'artk' => 'A',	'arte' => 10,	'arts' => 1,
			),
			21 => array
			(
			'name' => '⑨',
			'icon' => 1221,
			'gd' => 'f',
			'mhp' => 1800,
			'att' => 9,
			'def' =>9,
			'money' => 999,
			'club' => 0,
			'pls' => 99,
			'pose' => 4,
			'tactic' => 3,
			'skill' => 99,
			'wep' => '真·冰符『Icicle Fall』',
			'wepk' => 'WF',	'wepe' => 99,	'weps' => '∞',	'wepsk' => 'rNid|',
			'arb' => '⑨制冰衣',
			'arbk' => 'DB',	'arbe' => 99,	'arbs' => 99,	'arbsk' => 'Az',
			'arh' => '⑨制冰冠',
			'arhk' => 'DH',	'arhe' => 99,	'arhs' => 99,	'arhsk' => 'l',
			'arf' => '⑨制冰靴',
			'arfk' => 'DF',	'arfe' => 99,	'arfs' => 99,	'arfsk' => 'U',
			'ara' => '⑨制冰手链',
			'arak' => 'DA',	'arae' => 99,	'aras' => 9,	'arask' => 'H',
			'art' => '冰之自然妖精翼',
			'artk' => 'A',	'arte' => 9,	'arts' => 9,	'artsk' => 'cIZz',
			'itm1' => '真·⑨制冰块',
			'itmk1' => 'PB',	'itme1' => 99,	'itms1' => 99,	'itmsk1' => 'z',
			'itm2' => '智商',
			'itmk2' => 'A',	'itme2' => 9,	'itms2' => 9,	'itmsk2' => 'MH',
			'itm3' => '⑨的愤怒·冰天',
			'itmk3' => 'EW',	'itme3' => 1,	'itms3' => 1,	'itmsk3' => '13',
			),
			22 => array
			(
			'name' => '无姓之人',
			'icon' => 0,
			'pls' => 99,
			'gd' => 'r',
			'mhp' => 1999,
			'att' => 110,
			'def' => 150,
			'money' => 666,
			'skill' => 135,
			'pose' => 4,
			'tactic' => 3,
			'wep' => '涂满毒的砍刀',
			'wepk' => 'WK',	'wepe' => 120,	'weps' => 166,	'wepsk' => '|LnpV',
			'arb' => '肮脏的卫衣',
			'arbk' => 'DB',	'arbe' => 50,	'arbs' => 666,	'arbsk' => 'V',
			'arh' => '冰球面具',
			'arhk' => 'DH',	'arhe' => 30,	'arhs' => 666,	'arhsk' => 'V',
			'arf' => '肮脏的米色短裤',
			'arfk' => 'DF',	'arfe' => 30,	'arfs' => 666,	'arfsk' => 'V',
			'ara' => '中二病的绷带',
			'arak' => 'DA',	'arae' => 25,	'aras' => 666,	'arask' => 'cV',
			'art' => '网购的恶魔徽章',
			'artk' => 'A',	'arte' => 20,	'arts' => 20,	'artsk' => 'HAaV',
			'itm1' => '血污的磨刀石',
			'itmk1' => 'Y',	'itme1' => 50,	'itms1' => 4,	'itmsk1' => '',
			'itm2' => '有点奇怪的防殴咖啡★危险？',
			'itmk2' => 'PB',	'itme2' => 233,	'itms2' => 9,	'itmsk2' => 'Pz',
			),
			23 => array
			(
			'name'=>'二重弑',
			'icon' => 1223,
			'gd'=>'f',
			'mhp'=>3000,
			'att'=>200,
			'def'=>300,
			'lvl'=>20,
			'money'=>1600,
			'club'=>99,
			'pls'=>17,
			'pose'=>1,
			'tactic'=>3,
			'skill'=>0,
			'wep'=>'木棍？',
			'wepk'=>'WK',	'wepe'=>555,	'weps'=>200,	'wepsk'=>'Aadt',
			'arb'=>'和服',
			'arbk'=>'DB',	'arbe'=>600,	'arbs'=>100,
			'arh'=>'发簪',
			'arhk'=>'DH',	'arhe'=>600,	'arhs'=>100,
			'arf'=>'木屐',
			'arfk'=>'DF',	'arfe'=>600,	'arfs'=>200,
			'ara'=>'护袖',
			'arak'=>'DA',	'arae'=>600,	'aras'=>200,
			'art'=>'漆黑的宝石',
			'artk'=>'A',	'arte'=>20,	'arts'=>20,	'artsk'=>'H',
			'itm1'=>'高卡路里巧克力-一个就能补充一整天的行动力',
			'itmk1'=>'HS',	'itme1'=>900,	'itms1'=>100,	'itmsk1'=>'d',
			'itm2'=>'脑残酸菜泡椒牛肉面-一碗能补充一晚的战斗力',
			'itmk2'=>'HB',	'itme2'=>500,	'itms2'=>50,	'itmsk2'=>'c',
			'itm3'=>'H-GAME',
			'itmk3'=>'PS',	'itme3'=>500,	'itms3'=>10,	'itmsk4'=>'z',
			),
			24 => array
			(
			'name' => '魑魅',
			'icon' => 1224,
			'lvl' => 30,
			'gd' => 'f',
			'mhp' => 3000,
			'att' => 112,
			'def' => 112,
			'money' => 3000,
			'club' => 8,
			'pls' => 99,
			'pose' => 4,
			'tactic' => 3,
			'skill' => 200,
			'wep' => '魍魉的遗志',
			'wepk' => 'WN',	'wepe' => 86,	'weps' => '∞',	'wepsk' => 'rLpv',
			'arb' => '带毒的黑色风衣',
			'arbk' => 'DB',	'arbe' => 886,	'arbs' => 886,	'arbsk' => 'p',
			'arh' => '狰狞的毒瞳',
			'arhk' => 'DH',	'arhe' => 886,	'arhs' => 886,	'arhsk' => 'AHZ',
			'arf' => '腐烂的长鞋',
			'arfk' => 'DF',	'arfe' => 886,	'arfs' => 886,	'arfsk' => 'aMp',
			'ara' => '致残与进化的王之右手',
			'arak' => 'DA',	'arae' => 886,	'aras' => 886,	'arask' => 'LOx',
			'art' => '上古恶灵-魑魅',
			'artk' => 'A',	'arte' => 10,	'arts' => 10,	'artsk' => 'potV',
			'itm1' => '最终战术『银花』-改[+5]',
			'itmk1' => 'WG',	'itme1' => 86,	'itms1' => 16777215,	'itmsk1' => 'cdrvZ',
			/*
			'wep' => '无心天使',
			'wepk' => 'WN',	'wepe' => 188,	'weps' => '∞',	'wepsk' => 'rLv',
			'arb' => '幽灵羽衣',
			'arbk' => 'DB',	'arbe' => 886,	'arbs' => 886,	'arbsk' => 'c',
			'arh' => '邪王真眼',
			'arhk' => 'DH',	'arhe' => 886,	'arhs' => 886,	'arhsk' => 'aM',
			'arf' => '若风之蜕翼',
			'arfk' => 'DF',	'arfe' => 886,	'arfs' => 886,	'arfsk' => 'AHZ',
			'ara' => '致残与进化的王之右手',
			'arak' => 'DA',	'arae' => 886,	'aras' => 886,	'arask' => 'LOx',
			'art' => '成长的血海墨水心',
			'artk' => 'A',	'arte' => 886,	'arts' => 886,	'artsk' => '|m',
			'itm1' => '救济的祈愿',
			'itmk1' => 'HB',	'itme1' => 86,	'itms1' => '∞',	'itmsk1' => 'xz',
			'itm2' => '伤鸣的节拍',	'itmk2' => 'HM',	'itme2' => 50,	'itms2' => 1,	'itmsk2' => 'xz',
			'itm3' => '青刃的哀歌',	'itmk3' => 'HT',	'itme3' => 75,	'itms3' => 1,	'itmsk3' => 'xz',
			'itm4' => '★捆绑式炸药★',	'itmk4' => 'Z',	'itme4' => 1,	'itms4' => 3,	'itmsk4' => 'v',
			*/
			),
			25 => array(
			'name' => '大黑',
			'icon' => 1225,
			'gd' => 'm',
			'lvl' => 30,
			'mhp' => 2888,
			'att' => 88,
			'def' => 88,
			'money' => 888,
			'club' => 5,
			'pls' => 99,
			'pose' => 4,
			'tactic' => 1,
			'skill' => 100,
			'wep' => '最终战木『银花』[+4]-改',
			'wepk' => 'WD',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'duiwn',
			'arb' => '美洲人的华丽西装',
			'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'a',
			'arh' => '欧洲人的丑恶嘴脸',
			'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'DF',
			'arf' => '亚洲人的粗壮大腿',
			'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => 'ZH',
			'ara' => '澳洲人的袋鼠拳套',
			'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => '',
			'art' => '非洲人的终极信仰',
			'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'cx',
			'itm1' => '深海乌龙茶',
			'itmk1' => 'HB',	'itme1' => 88,	'itms1' => 888,	'itmsk1' => 'z',
			),
			26 => array(
			'name' => 'saki',
			'icon' => 0,
			'gd' => 'm',
			'mhp' => 2500,
			'att' => 100,
			'def' => 100,
			'money' => 2000,
			'club' => 70,
			'pls' => 99,
			'pose' => 2,
			'tactic' => 3,
			'skill' => 80,
			'wep' => '缺一块的贤者之石',
			'wepk' => 'WF',	'wepe' => 100,	'weps' => '∞',	'wepsk' => 'eipwZ',
			'arb' => '装着很多东西的背包',
			'arbk' => 'DB',	'arbe' => 800,	'arbs' => 600,	'arbsk' => 'GK',
			'arh' => 'saki的草帽',
			'arhk' => 'DH',	'arhe' => 800,	'arhs' => 600,	'arhsk' => 'D',
			'arf' => '抓来的乌龟',
			'arfk' => 'DF',	'arfe' => 900,	'arfs' => 900,	'arfsk' => 'Z',
			'ara' => 'saki的宝石手链',
			'arak' => 'DA',	'arae' => 900,	'aras' => 600,	'arask' => 'HF',
			'art' => '魔力结晶',
			'artk' => 'A',	'arte' => 1,	'arts' => 1,	'artsk' => 'acMm',
			'itm1' => '一盒子方块碎片',
			'itmk1' => 'jew',	'itme1' => 1,	'itms1' => 3,	'itmsk1' => 'Z',
			'itm2' => 'saki的真*阔剑地雷',
			'itmk2' => 'TN',	'itme2' => 2000,	'itms2' => 1,	'itmsk2' => 'Z',
			),
			27=>array(
			'name' => '一个路痴',
			'gd' => 'm',
			'icon' => 0,
			'mhp' => 3000,
			'att' => 200,
			'def' => 300,
			'lvl'=>20,
			'money' => 1600,
			'club' => 99,
			'pls' => 99,
			'pose' => 0,
			'tactic' => 2,
			'skill' => 25,
			'wep' => '双手',
			'wepk' => 'WN',	'wepe' => 200,	'weps' => 300,	'wepsk' => 'drNv',
			'arb' => '普通的衣服',
			'arbk' => 'DB',	'arbe' => 600,	'arbs' => 100,	'arbsk' => '',
			'arh' => '破旧的眼镜',
			'arhk' => 'DH',	'arhe' => 600,	'arhs' => 100,	'arhsk' => 'Aa',
			'arf' => '会吸引地雷的脚',
			'arfk' => 'DF',	'arfe' => 600,	'arfs' => 100,	'arfsk' => '',
			'ara' => '瘦弱的手臂',
			'arak' => 'DA',	'arae' => 600,	'aras' => 100,	'arask' => '',
			'art' => '看不懂的地图',
			'artk' => 'A',	'arte' => 20,	'arts' => 20,	'artsk' => 'H',
			),
		),
	),
	13 => array
		(
		'num' => 1,
		'pass' => 'bra',
		'gd' => 'f',//
		'icon' => 222,
		'club' => 99,
		'mhp' => 1000,//500####2300
		'msp' => 200,//200####200
		'att' => 50,//130+50####250+75
		'def' => 400,//150+110####350+375
		'pls' => 25,
		'lvl' => 45,//10####25
		'skill' => 0,//40####135
		'money' => 0,//220####1600
		'rage' => 0,
		'pose' => 0,
		'tactic' => 0,	
		'teamID' => '',
		'teamPass' => '',
		'bid' => 0,
		'sub' => array
			(
			0=> array
				(
				
				'icon' => 222,
				'name' => '亚莉丝',
				'wep' => '软绵无力的拳头',
				'wepk' => 'WN',	'wepe' => 1,	'weps' => 9999,	'wepsk' => 'rv',
				'arb' => '亚莉丝的朴素连衣裙',
				'arbk' => 'DB',	'arbe' => 200,	'arbs' => 200,	'arbsk' => 'H',
				'arh' => '亚莉丝的遮阳草帽',
				'arhk' => 'DH',	'arhe' => 200,	'arhs' => 200,	'arhsk' => 'A',
				'arf' => '亚莉丝的露趾凉鞋',
				'arfk' => 'DF',	'arfe' => 200,	'arfs' => 200,	'arfsk' => 'a',
				'itm6' => '集换卡片-亚莉丝',
				'itmk6' => 'WC',	'itme6' => 340,	'itms6' => 75,	'itmsk6' => 'dr',
				'itm1' => '代码聚合体的ID卡',
				'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 1,	'itmsk1' => '',
				
				/*
				'icon' => 225,
				'name' => '欢庆型亚莉丝',
				'club' => 70,
				'pose' => 6,
				'mhp' => 30000,
				'skill' => 275,
				'wep' => '喜庆礼炮',
				'wepk' => 'WG',	'wepe' => 340,	'weps' => 9999,	'wepsk' => 'dRvz',
				'arb' => '感觉轻飘飘的女仆装',
				'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'Z',
				'arh' => '附带装饰猫耳的女仆发箍',
				'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'AZ',
				'arf' => '精巧可爱的小皮靴',
				'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => 'aZ',
				'ara' => '毛茸茸的猫掌手套',
				'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => 'Z',
				'art' => '附带装饰猫尾的腰带',
				'artk' => 'A',	'arte' => 10,	'arts' => 10,	'artsk' => 'bHv',
				'itm6' => '集换卡片-亚莉丝',
				'itmk6' => 'WC',	'itme6' => 340,	'itms6' => 75,	'itmsk6' => 'dr',
				'itm1' => '游戏解除钥匙',
				'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 1,	'itmsk1' => '',
				'itm2' => '蛋糕',
				'itmk2' => 'HH',	'itme2' => 1000,	'itms2' => 20,	'itmsk2' => '',
				'itm3' => '红茶',
				'itmk3' => 'HS',	'itme3' => 1000,	'itms3' => 20,	'itmsk3' => '',
				*/
				),
			),
		),
	14 => array
		(
		'num' => 2,
		'pass' => 'bra',
		'gd' => 'm',//
		'icon' => 0,
		'club' => 0,
		'mhp' => 500,//500####2300
		'msp' => 200,//200####200
		'att' => 150,//130+50####250+75
		'def' => 150,//150+110####350+375
		'pls' => 24,
		'lvl' => 15,//10####25
		'skill' => 60,//40####135
		'money' => 400,//220####1600
		'rage' => 0,
		'pose' => 0,
		'tactic' => 0,	
		'teamID' => '',
		'teamPass' => '',
		'bid' => 0,
		'arb' => '投影-数据错误',	'arbk' => 'DB',	'arbe' => 25,	'arbs' => 30,	'arbsk' => '',
		'arh' => '投影-数据错误',	'arhk' => 'DH',	'arhe' => 25,	'arhs' => 30,	'arhsk' => '',
		'arf' => '投影-数据错误',	'arfk' => 'DF',	'arfe' => 25,	'arfs' => 30,	'arfsk' => '',
		'ara' => '投影-数据错误',	'arak' => 'DA',	'arae' => 25,	'aras' => 30,	'arask' => '',
		'sub' => array
			(
			0=> array
				(
				'name' => '投影-零教授',
				'icon' => 0,
				'wep' => '投影-水素粒子水铁炮',
				'wepk' => 'WDG',	'wepe' => 50,	'weps' => 200,	'wepsk' => 'cd',
				'itm1' => '集换卡片-零教授',
				'itmk1' => 'WC',	'itme1' => 120,	'itms1' => 75,	'itmsk1' => 'L',
				),
			1=> array
				(
				'name' => '投影-雁落孤城',
				'icon' => 0,
				'wep' => '投影-巫女狩猎',
				'wepk' => 'WKP',	'wepe' => 70,	'weps' => 200,	'wepsk' => 'cer',
				'itm1' => '集换卡片-雁落孤城',
				'itmk1' => 'WC',	'itme1' => 120,	'itms1' => 75,	'itmsk1' => 'de',
				'itm2' => '笔记本电脑',
				'itmk2' => 'X',	'itme2' => 1,	'itms2' => 1,	'itmsk2' => '',
				'itm3' => '手机',
				'itmk3' => 'X',	'itme3' => 1,	'itms3' => 1,	'itmsk3' => '',
				'itm4' => '电池',
				'itmk4' => 'BE',	'itme4' => 2,	'itms4' => 1,	'itmsk4' => '',
				'itm5' => '生命探测器',
				'itmk5' => 'ER',	'itme5' => 1,	'itms5' => 1,	'itmsk5' => '',
				),
			),
		),
	40 => array
		(
		'mode' => 1,
		'num' => 15,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'r',
		'pls' => 19,
		'mhp' => 500,
		'msp' => 200,
		'att' => 130,
		'def' => 150,
		'lvl' => 10,
		'skill' => 40,
		'money' => 220,
		
		'arf' => '皮鞋',
		'arfk' => 'DF',
		'arfe' => 25,
		'arfs' => 30,
		
		'ara' => '医用手套',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 30,
		
		//'art' => 'ACFUN的账号',
		//'artk' => 'A',
		//'arte' => 20,
		//'arts' => 10,
		//'itm4' => '锅？',
		//'itmk4' => 'Y',
		//'itme4' => 1,
		//'itms4' => 1,
		//'itm5' => '好人卡',
		//'itmk5' => 'Y',
		//'itme5' => 1,
		//'itms5' => 15,
		//'itm6' => '压缩饼干',
		//'itmk6' => 'HB',
		//'itme6' => 35,
		//'itms6' => 10,
		
		'sub' => array
		(
		 0 => array
			(
			'name' => '医生',
			'icon' => 21,
			'wep' => '手术刀',
			'wepk' => 'WK',
			'wepe' => 50,
			'weps' => 50,
			'arb' => '白衣',
			'arbk' => 'DB',
			'arbe' => 40,
			'arbs' => 30,
			'itm1' => '营养素',
			'itmk1' => 'Y',
			'itme1' => 1,
			'itms1' => 1,
			'itm2' => '喷雾器罐',
			'itmk2' => 'Y',
			'itme2' => 1,
			'itms2' => 1,
			'itm3' => '营养饮料',
			'itmk3' => 'HS',
			'itme3' => 100,
			'itms3' => 1,
			'itm5' => '解毒剂',
			'itmk5' => 'Cp',
			'itme5' => 1,
			'itms5' => 1,
			),
		1 => array
			(
			'name' => '护士',
			'gd' => 'f',
			'icon' => 22,
			'wep' => '注射器',
			'wepk' => 'WC',
			'wepe' => 45,
			'weps' => 50,
			'arb' => '护士服',
			'arbk' => 'DB',
			'arbe' => 40,
			'arbs' => 30,
			'arh' => '护士帽',
			'arhk' => 'DH',
			'arhe' => 25,
			'arhs' => 30,
			'itm1' => '特效药',
			'itmk1' => 'HH',
			'itme1' => 120,
			'itms1' => 1,
			'itm2' => '毒药',
			'itmk2' => 'Y',
			'itme2' => 1,
			'itms2' => 5,
			'itm5' => '烧伤药剂',
			'itmk5' => 'Cu',
			'itme5' => 1,
			'itms5' => 1,
			),
		),
	),
	
	41 => array
		(
		'mode' => 2,//巫女众
		'num' => 60,
		'pass' => 'bra',
		'gd' => 'f',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'pls' => 99,
		'mhp' => 2300,
		'msp' => 200,
		'att' => 250,
		'def' => 350,
		'lvl' => 25,
		'skill' => 135,
		'money' => 1600,
		'arb' => '巫女服',
		'arbk' => 'DB',
		'arbe' => 150,
		'arbs' => 100,
		//'arh' => '帽子',
		//'arhk' => 'DH',
		//'arhe' => 75,
		//'arhs' => 100,
		'arf' => '木屐',
		'arfk' => 'DF',
		'arfe' => 75,
		'arfs' => 100,
		//'ara' => '饰品',
		//'arak' => 'DA',
		//'arae' => 75,
		//'aras' => 100,
		'itm5' => '御神签',
		'itmk5' => 'Y',
		'itme5' => 1,
		'itms5' => 3,
		'sub' => array
			(
			0 => array
			  (
			'name' => '留守打扫的巫女',
			'icon' => 11,
			'mode' => 1,
			'pls' => 8,
			'wep' => '扫帚',
			'wepk' => 'WP',
			'wepe' => 75,
			'weps' => 200,
			'itm1' => '水',
			'itmk1' => 'HH',
			'itme1' => 30,
			'itms1' => 10,
			//'itmsk1' => 'id',
			'itm2' => '灵子符',
			'itmk2' => 'WD',
			'itme2' => 45,
			'itms2' => 10,
			//'itmsk2' => 'r',
			'itm2' => '白诘草印章',
			'itmk2' => 'Y',
			'itme2' => 1,
			'itms2' => 1,
			),
			1 => array
			  (
			'name' => '使太刀的巫女',
			'icon' => 11,
			'wep' => '太刀',
			'wepk' => 'WK',
			'wepe' => 75,
			'weps' => 200,
			'itm1' => '水',
			'itmk1' => 'HS',
			'itme1' => 45,
			'itms1' => 10,
			'itm2' => '毒药',
			'itmk2' => 'Y',
			'itme2' => 1,
			'itms2' => 3,
			'itm3' => '磨刀石',
			'itmk3' => 'Y',
			'itme3' => 1,
			'itms3' => 1,
			),
			2 => array
			  (
			'name' => '使镰刀的巫女',
			'icon' => 11,
			'wep' => '镰刀',
			'wepk' => 'WK',
			'wepe' => 75,
			'weps' => 200,
			'itm1' => '便当',
			'itmk1' => 'HS',
			'itme1' => 280,
			'itms1' => 10,
			'itm2' => '馊掉的紧急食粮',
			'itmk2' => 'PH',
			'itme2' => 200,
			'itms2' => 1,
			'itm3' => '受潮的灵子符',
			'itmk3' => 'WD',
			'itme3' => 10,
			'itms3' => 10,
			),
			3 => array
			  (
			'name' => '使十字弩的巫女',
			'icon' => 11,
			'wep' => '十字弩',
			'wepk' => 'WGK',
			'wepe' => 75,
			'weps' => 200,
			'itm1' => '水',
			'itmk1' => 'HS',
			'itme1' => 90,
			'itms1' => 5,
			'itm2' => '馊掉的紧急食粮',
			'itmk2' => 'PH',
			'itme2' => 200,
			'itms2' => 1,
			'itm3' => '疗伤药',
			'itmk3' => 'HH',
			'itme3' => 200,
			'itms3' => 3,
			),
			4 => array
			  (
			'name' => '使灵子符的巫女',
			'icon' => 11,
			'att' => 275,
			'wep' => '灵子符',
			'wepk' => 'WD',
			'wepe' => 75,
			'weps' => 200,
			'itm1' => '水',
			'itmk1' => 'HS',
			'itme1' => 90,
			'itms1' => 5,
			'itm2' => '白诘草印章',
			'itmk2' => 'Y',
			'itme2' => 1,
			'itms2' => 1,
			'itm3' => '灵子符',
			'itmk3' => 'WD',
			'itme3' => 75,
			'itms3' => 150,
			),
		),
	),
	
	43 => array
		(
		'mode' => 2,//下级小兵基准
		'num' => 8,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'r',
		'pls' => 99,
		'mhp' => 500,
		'msp' => 200,
		'att' => 130,
		'def' => 150,
		'lvl' => 10,
		'skill' => 40,
		'money' => 220,
		'arb' => '白衣',
		'arbk' => 'DB',
		'arbe' => 35,
		'arbs' => 30,
		'arf' => '皮鞋',
		'arfk' => 'DF',
		'arfe' => 25,
		'arfs' => 30,
		'ara' => '手套',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 30,
		'wep' => '掌心枪',
		'wepk' => 'WG',
		'wepe' => 45,
		'weps' => 50,
		'sub' => array
		(
		 0 => array
			(
			'name' => '地质研究员',
			'icon' => 21,
			'itm1' => '盒饭',
			'itmk1' => 'HB',
			'itme1' => 150,
			'itms1' => 1,
			),
		1 => array
			(
			'name' => '气候研究员',
			'icon' => 22,
			'itm1' => '美味三明治',
			'itmk1' => 'HS',
			'itme1' => 120,
			'itms1' => 3,
			'itm1' => '天候棒',
			'itmk1' => 'Y',
			'itme1' => 1,
			'itms1' => 3,
			),
		2 => array
			(
			'name' => '灵学研究员',
			'pls' => 15,
			'mode' => 1,
			'icon' => 21,
			'itm1' => '试验用灵子符',
			'itmk1' => 'WD',
			'itme1' => 150,
			'itms1' => 1,
			),
		3 => array
			(
			'name' => '植物研究员',
			'icon' => 22,
			'itm1' => '美味三明治',
			'itmk1' => 'HS',
			'itme1' => 120,
			'itms1' => 3,
			),
		),
	),
	89 => array
		(
		'mode' => 2,
		'num' => 40,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'gd' => 'm',
		'teamID' => '',
		'teamPass' => '',
		'pls' => 99,
		'mhp' => 2300,
		'msp' => 200,
		'att' => 250,
		'def' => 350,
		'lvl' => 25,
		'skill' => 135,
		'money' => 1600,
		'arb' => '军服β',
		'arbk' => 'DB',
		'arbe' => 150,
		'arbs' => 100,
		'arh' => '军帽β',
		'arhk' => 'DH',
		'arhe' => 75,
		'arhs' => 100,
		'arf' => '军靴β',
		'arfk' => 'DF',
		'arfe' => 75,
		'arfs' => 100,
		'ara' => '军用手套β',
		'arak' => 'DA',
		'arae' => 75,
		'aras' => 100,
		//'itm5' => '好人卡',
		//'itmk5' => 'Y',
		//'itme5' => 1,
		//'itms5' => 16,
		'sub' => array
			(
			0 => array
			  (
			'name' => '甲',
			'icon' => 11,
			'wep' => '军用狙击枪β',
			'wepk' => 'WG',
			'wepe' => 75,
			'weps' => 200,
			),
			1 => array
			(
			'name' => '乙',
			'icon' => 11,
			'wep' => '军杖',
			'wepk' => 'WP',
			'wepe' => 75,
			'weps' => 200,
			),
			2 => array
			(
			'name' => '丙',
			'icon' => 11,
			'wep' => '军刀',
			'wepk' => 'WK',
			'wepe' => 75,
			'weps' => 200,
			),
			3 => array
			(
			'name' => '丁',
			'icon' => 20,
			'att' => 300,
			'wep' => '军用飞刀',
			'wepk' => 'WC',
			'wepe' => 75,
			'weps' => 200,
			),
		),
	),
	42 => array
		(
		'mode' => 2,
		'num' => 1,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'm',
		'pls' => 99,
		'mhp' => 300,
		'msp' => 200,
		'att' => 70,
		'def' => 150,
		'lvl' => 5,
		'skill' => 40,
		'money' => 450,
		'arb' => '制服',
		'arbk' => 'DB',
		'arbe' => 15,
		'arbs' => 15,
		
		//'arh' => '锅外形的帽子',
		//'arhk' => 'DH',
		//'arhe' => 25,
		//'arhs' => 30,
		
		'arf' => '皮鞋',
		'arfk' => 'DF',
		'arfe' => 12,
		'arfs' => 30,
		
		///'ara' => '军用手套β',
		//'arak' => 'DA',
		//'arae' => 25,
		//'aras' => 30,
		
		'art' => '教师资格证',
		'artk' => 'A',	'arte' => 1,	'arts' => 1, 'artsk' => 'HM',
		
		'sub' => array
		(
		 0 => array
			(
			'name' => '任林田',
			'icon' => 4200,
			'wep' => '锅铲型狙击枪',
			'wepk' => 'WP',
			'wepe' => 25,
			'weps' => 25,
			'itm1' => '打火机',
			'itmk1' => 'Y',	'itme1' => 1,	'itms1' => 1,	'itmsk1' => '',
			),
		),
	),
	90 => array
		(
		'mode' => 2,
		'num' => 240,
		'pass' => 'bra',
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 0,
		'tactic' => 0,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'm',
		'pls' => 99,
		'mhp' => 500,
		'msp' => 200,
		'att' => 130,
		'def' => 150,
		'lvl' => 10,
		'skill' => 40,
		'money' => 220,
		'arb' => '锅外形的背包',
		'arbk' => 'DB',
		'arbe' => 35,
		'arbs' => 30,
		
		'arh' => '锅外形的帽子',
		'arhk' => 'DH',
		'arhe' => 25,
		'arhs' => 30,
		
		'arf' => '军靴β',
		'arfk' => 'DF',
		'arfe' => 25,
		'arfs' => 30,
		
		'ara' => '军用手套β',
		'arak' => 'DA',
		'arae' => 25,
		'aras' => 30,
		
		'art' => '无聊证明书',
		'artk' => 'A',
		'arte' => 20,
		'arts' => 10,
		//'itm4' => '锅？',
		//'itmk4' => 'Y',
		//'itme4' => 1,
		//'itms4' => 1,
		'itm6' => '压缩饼干',
		'itmk6' => 'HB',
		'itme6' => 35,
		'itms6' => 10,
		//'itm5' => '好人卡',
		//'itmk5' => 'Y',
		//'itme5' => 1,
		//'itms5' => 15,
		
		'sub' => array
		(
		0 => array
			(
			'name' => '量产型无聊A',
			'icon' => 21,
			'wep' => '锅铲型狙击枪',
			'wepk' => 'WG',
			'wepe' => 50,
			'weps' => 50,
			//'itm5' => '解毒剂',
			//'itmk5' => 'Cp',
			//'itme5' => 1,
			//'itms5' => 1,
			),
		1 => array
			(
			'name' => '量产型无聊B',
			'icon' => 22,
			'wep' => '擀面杖型军杖',
			'wepk' => 'WP',
			'wepe' => 50,
			'weps' => 50,
			//'itm5' => '烧伤药剂',
			//'itmk5' => 'Cu',
			//'itme5' => 1,
			//'itms5' => 1,
			),
		2 => array
			(
			'name' => '量产型无聊C',
			'icon' => 24,
			'wep' => '便利菜刀',
			'wepk' => 'WK',
			'wepe' => 50,
			'weps' => 50,
			//'itm5' => '解冻药水',
			//'itmk5' => 'Ci',
			//'itme5' => 1,
			//'itms5' => 1,
			),
		),
	),
	
	//显示介绍用的
	25 => array
		(
		'mode' => 1,
		'num' => 0,
		'pass' => 'fklnzg20',
		'bid' => 0,
		'inf' => '',
		'rage' => 100,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teampsss' => '',
		'pls' => 99,
		'art' => '契约书',
		'artk' => 'A',
		'arte' => 1,
		'arts' => 1,
		'artsk' => 'H',
		'money' => 1200,
		'sub' => array
		(
			0 => array
			(
			'club' => 0,
			'name' => '肥宅',
			'icon' => 150,
			'pose'=> 0,
			'gd' => 'm',
			'mhp' => 300,
			'msp' => 400,
			'att' => 5,
			'def' => 50,
			'lvl' => 1,
			'skill' => 5,
			'wep' => '我好兴奋啊！',
			'wepk' => 'WF',
			'wepe' => 7,
			'weps' => 999,
			'wepsk' => 'w',
			'arb' => '不合身的衬衫',
			'arbk' => 'DB',
			'arbe' => 5,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '包头巾',
			'arhk' => 'DH',
			'arhe' => 5,
			'arhs' => 12,
			'arhsk' => '',
			'arf' => '人字拖',
			'arfk' => 'DF',
			'arfe' => 2,
			'arfs' => 5,
			'arfsk' => '',
			'ara' => '佐佑酱',
			'arak' => 'DA',
			'arae' => 5,
			'aras' => 2,
			'arask' => 'c',
			),
			1 => array
			(
			'club' => 17,
			'name' => '春原 阳平',
			'icon' => 151,
			'pose'=> 0,
			'gd' => 'm',
			'mhp' => 400,
			'msp' => 400,
			'att' => 120,
			'def' => 250,
			'lvl' => 5,
			'skill' => 100,
			'wep' => '马桶盖子',
			'wepk' => 'WP',
			'wepe' => 50,
			'weps' => 50,
			'wepsk' => '',
			'arb' => '光坂高校校服',
			'arbk' => 'DB',
			'arbe' => 22,
			'arbs' => 22,
			'arbsk' => '',
			'arh' => '马桶盖子',
			'arhk' => 'DH',
			'arhe' => 22,
			'arhs' => 22,
			'arhsk' => '',
			'arf' => '光坂高校校裤',
			'arfk' => 'DF',
			'arfe' => 22,
			'arfs' => 22,
			'arfsk' => '',
			'ara' => '马桶盖子',
			'arak' => 'DA',
			'arae' => 22,
			'aras' => 22,
			'arask' => '',
			),
			2 => array
			(
			'club' => 11,
			'name' => '真猎人',
			'icon' => 152,
			'pose'=> 0,
			'gd' => 'm',
			'mhp' => 850,
			'msp' => 400,
			'att' => 120,
			'def' => 450,
			'lvl' => 5,
			'skill' => 140,
			'wep' => '破解的二手PSP2000',
			'wepk' => 'WP',
			'wepe' => 200,
			'weps' => 20,
			'wepsk' => 'e',
			'arb' => '真猎人的追求',
			'arbk' => 'DB',
			'arbe' => 80,
			'arbs' => 80,
			'arbsk' => '',
			'arh' => '真猎人的坚持',
			'arhk' => 'DH',
			'arhe' => 80,
			'arhs' => 80,
			'arhsk' => '',
			'arf' => '真猎人的倔强',
			'arfk' => 'DF',
			'arfe' => 80,
			'arfs' => 80,
			'arfsk' => '',
			'ara' => '真猎人的信念',
			'arak' => 'DA',
			'arae' => 80,
			'aras' => 80,
			'arask' => '',
			),
			3 => array
			(
			'club' => 9,
			'name' => '彩虹独角兽',
			'icon' => 153,
			'pose'=> 2,
			'gd' => 'f',
			'mhp' => 1000,
			'msp' => 1000,
			'att' => 350,
			'def' => 650,
			'lvl' => 17,
			'skill' => 200,
			'wep' => '友谊魔法',
			'wepk' => 'WF',
			'wepe' => 200,
			'weps' => 200,
			'wepsk' => 'x',
			'arb' => '诚实与魔法',
			'arbk' => 'DB',
			'arbe' => 120,
			'arbs' => 80,
			'arbsk' => '',
			'arh' => '忠诚与慷慨',
			'arhk' => 'DH',
			'arhe' => 120,
			'arhs' => 80,
			'arhsk' => '',
			'arf' => '小马的腿',
			'arfk' => 'DF',
			'arfe' => 120,
			'arfs' => 80,
			'arfsk' => '',
			'ara' => '善良与欢笑',
			'arak' => 'DA',
			'arae' => 120,
			'aras' => 80,
			'arask' => '',
			),
			4 => array
			(
			'club' => 9,
			'name' => '海星王',
			'icon' => 154,
			'pose'=> 2,
			'gd' => 'm',
			'mhp' => 1600,
			'msp' => 1000,
			'att' => 250,
			'def' => 650,
			'lvl' => 17,
			'skill' => 200,
			'wep' => '黑魔导女孩',
			'wepk' => 'WC06',
			'wepe' => 250,
			'weps' => 300,
			'wepsk' => 'r',
			'arb' => '千年积木',
			'arbk' => 'DB',
			'arbe' => 170,
			'arbs' => 80,
			'arbsk' => '',
			'arh' => '法老之眼',
			'arhk' => 'DH',
			'arhe' => 160,
			'arhs' => 80,
			'arhsk' => '',
			'arf' => '海鲜之力',
			'arfk' => 'DF',
			'arfe' => 160,
			'arfs' => 80,
			'arfsk' => '',
			'ara' => '神抽之手',
			'arak' => 'DA',
			'arae' => 200,
			'aras' => 80,
			'arask' => 'x',
			),
			5 => array
			(
			'club' => 9,
			'name' => '红帽少年',
			'icon' => 155,
			'pose'=> 2,
			'gd' => 'm',
			'mhp' => 1500,
			'msp' => 1000,
			'att' => 450,
			'def' => 450,
			'lvl' => 19,
			'skill' => 400,
			'wep' => '黄色老鼠',
			'wepk' => 'WC',
			'wepe' => 600,
			'weps' => 300,
			'wepsk' => 'e',
			'arb' => '蓝色马甲',
			'arbk' => 'DB',
			'arbe' => 200,
			'arbs' => 80,
			'arbsk' => 'G',
			'arh' => '红色鸭舌帽',
			'arhk' => 'DH',
			'arhe' => 220,
			'arhs' => 80,
			'arhsk' => 'FD',
			'arf' => '牛仔裤',
			'arfk' => 'DF',
			'arfe' => 200,
			'arfs' => 80,
			'arfsk' => 'a',
			'ara' => '露指手套',
			'arak' => 'DA',
			'arae' => 200,
			'aras' => 80,
			'arask' => 'P',
			),
			6 => array
			(
			'club' => 4,
			'name' => '海豹部队',
			'icon' => 156,
			'pose'=> 2,
			'gd' => 'm',
			'mhp' => 1400,
			'msp' => 1400,
			'att' => 750,
			'def' => 750,
			'lvl' => 25,
			'skill' => 400,
			'wep' => 'HK MP5',
			'wepk' => 'WG',
			'wepe' => 220,
			'weps' => 600,
			'wepsk' => 'r',
			'arb' => '战术背心',
			'arbk' => 'DB',
			'arbe' => 300,
			'arbs' => 80,
			'arbsk' => 'GK',
			'arh' => '战术钢盔',
			'arhk' => 'DH',
			'arhe' => 300,
			'arhs' => 80,
			'arhsk' => 'GD',
			'arf' => '迷彩军裤',
			'arfk' => 'DF',
			'arfe' => 300,
			'arfs' => 80,
			'arfsk' => '',
			'ara' => '战斗手套',
			'arak' => 'DA',
			'arae' => 250,
			'aras' => 80,
			'arask' => 'GP',
			),
			7 => array
			(
			'club' => 9,
			'name' => '圣德太子',
			'icon' => 157,
			'pose'=> 2,
			'gd' => 'f',
			'mhp' => 5500,
			'msp' => 2400,
			'att' => 550,
			'def' => 850,
			'lvl' => 25,
			'skill' => 600,
			'wep' => '十七条黄金传染病',
			'wepk' => 'WF',
			'wepe' => 200,
			'weps' => 600,
			'wepsk' => 'r',
			'arb' => '星辰披风',
			'arbk' => 'DB',
			'arbe' => 200,
			'arbs' => 80,
			'arbsk' => 'Fa',
			'arh' => '日和耳机',
			'arhk' => 'DH',
			'arhe' => 200,
			'arhs' => 80,
			'arhsk' => 'W',
			'arf' => '华贵长裙',
			'arfk' => 'DF',
			'arfe' => 200,
			'arfs' => 80,
			'arfsk' => '',
			'ara' => '金色缠腕',
			'arak' => 'DA',
			'arae' => 150,
			'aras' => 80,
			'arask' => '',
			),
			8 => array
			(
			'club' => 4,
			'name' => 'FV4202',
			'icon' => 158,
			'pose'=> 2,
			'gd' => 'm',
			'mhp' => 5000,
			'msp' => 2400,
			'att' => 850,
			'def' => 350,
			'lvl' => 20,
			'skill' => 500,
			'wep' => '105mm Royal L7',
			'wepk' => 'WG',
			'wepe' => 500,
			'weps' => 600,
			'wepsk' => 'cd',
			'arb' => '坦克装甲',
			'arbk' => 'DB',
			'arbe' => 400,
			'arbs' => 180,
			'arbsk' => 'a',
			'arh' => '炮盾',
			'arhk' => 'DH',
			'arhe' => 400,
			'arhs' => 180,
			'arhsk' => 'D',
			'arf' => '重型履带',
			'arfk' => 'DF',
			'arfe' => 400,
			'arfs' => 180,
			'arfsk' => '',
			'ara' => '坦克装甲',
			'arak' => 'DA',
			'arae' => 400,
			'aras' => 180,
			'arask' => 'G',
			),
			9 => array
			(
			'club' => 2,
			'name' => '萨鲁法尔大王',
			'icon' => 159,
			'pose'=> 2,
			'gd' => 'm',
			'mhp' => 24000,
			'msp' => 2400,
			'att' => 800,
			'def' => 750,
			'lvl' => 40,
			'skill' => 800,
			'wep' => '高阶督军的斩首斧',
			'wepk' => 'WK',
			'wepe' => 1600,
			'weps' => 600,
			'wepsk' => 'Nnc',
			'arb' => '高阶督军的铠甲',
			'arbk' => 'DB',
			'arbe' => 100,
			'arbs' => 180,
			'arbsk' => 'ZAa',
			'arh' => '高阶督军的钢盔',
			'arhk' => 'DH',
			'arhe' => 500,
			'arhs' => 180,
			'arhsk' => 'D',
			'arf' => '高阶督军的战靴',
			'arfk' => 'DF',
			'arfe' => 500,
			'arfs' => 180,
			'arfsk' => '',
			'ara' => '高阶督军的护手',
			'arak' => 'DA',
			'arae' => 500,
			'aras' => 180,
			'arask' => '',
			),
			10 => array
			(
			'club' => 14,
			'name' => 'Chuck Norris',
			'icon' => 160,
			'pose'=> 2,
			'gd' => 'm',
			'mhp' => 18000,
			'msp' => 2400,
			'att' => 1000,
			'def' => 1000,
			'lvl' => 40,
			'skill' => 800,
			'wep' => '阿姆斯特朗回旋踢',
			'wepk' => 'WP',
			'wepe' => 1900,
			'weps' => 600,
			'wepsk' => 'N',
			'arb' => '硬汉的躯体',
			'arbk' => 'DB',
			'arbe' => 200,
			'arbs' => 180,
			'arbsk' => 'ZAa',
			'arh' => '硬汉的气魄',
			'arhk' => 'DH',
			'arhe' => 700,
			'arhs' => 180,
			'arhsk' => 'D',
			'arf' => '硬汉的灵敏',
			'arfk' => 'DF',
			'arfe' => 700,
			'arfs' => 180,
			'arfsk' => '',
			'ara' => '硬汉的铁拳',
			'arak' => 'DA',
			'arae' => 700,
			'aras' => 180,
			'arask' => '',
			),
		),
	),

	17 => array(
		'num' => 0,
		'pass' => 'bra',
		'icon' => 0,
		'club' => 0,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 1,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'pls' => 22,
		'mhp' => 2500,
		'msp' => 200,
		'att' => 88,
		'def' => 88,
		'lvl' => 30,
		'skill' => 100,
		'money' => 888,
		'icon' => 0,
		'wep' => '？？？',
		'wepk' => 'WN',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'v',
		'arb' => '深渊迷雾',
		'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'v',
		'arh' => '深渊迷雾',
		'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'v',
		'arf' => '深渊迷雾',
		'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => 'v',
		'ara' => '深渊迷雾',
		'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => 'v',
		'art' => '深渊迷雾',
		'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'Hv',
		'sub' => array
		(
			0 => array
			(
			'name' => '白后娜美',
			'icon' => 0,
			'wep' => '不知从哪里拆下来的钢管',
			'wepk' => 'WP',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'rnv',
			'arb' => '白色连衣裙',
			'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'A',
			'arh' => '白色发卡',
			'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => '',
			'arf' => '白色凉鞋',
			'arfk' => 'DF',	'arfe' => 888,	'arfs' => 888,	'arfsk' => '',
			'ara' => '白色腕环',
			'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => 'z',
			'art' => '白色十字架项链',
			'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'aH',
			),
			1 => array
			(
			'name' => '怀特迈恩准将',
			'icon' => 0,
			'gd' => 'f',
			'skill' => 600,
			'pose' => 4,
			'wep' => 'X-32激光枪',
			'wepk' => 'WG',	'wepe' => 150,	'weps' => 10,	'wepsk' => 'v',
			'arb' => '拟态护甲',
			'arbk' => 'DB',	'arbe' => 50,	'arbs' => 60,	'arbsk' => '',
			'arh' => '钢盔',
			'arhk' => 'DH',	'arhe' => 40,	'arhs' => 20,	'arhsk' => '',
			'arf' => '帝国标配军靴',
			'arfk' => 'DF',	'arfe' => 25,	'arfs' => 50,	'arfsk' => '',
			'ara' => '拟肤手套',
			'arak' => 'DA',	'arae' => 40,	'aras' => 40,	'arask' => '',
			'art' => '帝国的荣耀戒指',
			'artk' => 'A',	'arte' => 40,	'arts' => 20,	'artsk' => 'vH',			
			),
			2 => array
			(
			'name' => '镰刀子',
			'icon' => 0,
			'gd' => 'f',
			'wep' => '镰刀',
			'wepk' => 'WK',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'v',
			'arb' => '午夜斗篷',
			'arbk' => 'DB',	'arbe' => 88,	'arbs' => 888,	'arbsk' => '',
			'art' => '巡夜提灯',
			'artk' => 'A',	'arte' => 40,	'arts' => 20,	'artsk' => 'vH',			
			),
			3 => array
			(
			'name' => '河童',
			'icon' => 0,
			'skill' => 600,
			'pose' => 4,
			'wep' => 'Lucifer本子',
			'wepk' => 'WF',	'wepe' => 88,	'weps' => 888,	'wepsk' => 'v',
			'arb' => '水手服',
			'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => '',
			'arh' => '蝴蝶结',
			'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => '',
			'ara' => '白手套',
			'arak' => 'DA',	'arae' => 888,	'aras' => 888,	'arask' => '',
			'art' => '项圈',
			'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'vH',			
			),
			4 => array
			(
			'name' => '邪心梦魇',
			'icon' => 0,
			'gd' => 'r',
			'skill' => 600,
			'pose' => 1,
			'tactic' => 2,
			'wep' => '血誓',
			'wepk' => 'WN',	'wepe' => 1300,	'weps' => 50,	'wepsk' => 'n=v',
			'arb' => '血食翼服',
			'arbk' => 'DB',	'arbe' => 888,	'arbs' => 888,	'arbsk' => 'a',
			'arh' => '魇之角',
			'arhk' => 'DH',	'arhe' => 888,	'arhs' => 888,	'arhsk' => 'A',
			'art' => '魇纹',
			'artk' => 'A',	'arte' => 5,	'arts' => 5,	'artsk' => 'lVH',			
			),
		),
	),

);





$npcdescription = array
( 
/*	1 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '红杀将军 红暮，坐镇于无月之影的BOSS，达成锁定解除结局所必须击杀的NPC。 <span class="yellow">没事还是不要惹她好了……</span>',
			),
		),
	),*/
	1 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '万恶之源。',
			),
		),
	),
	2 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '陆军作战部的头领。老练的作战经验让敌人闻风丧胆。',
			),
			1 => array
			(
				'count' => 1,
				'description' => '高新科技军武开发部主任。富有少女心的她却发明制造了许多不人道而穷凶极恶的战斗武器。本人似乎不擅长战斗。',
			),
			2 => array
			(
				'count' => 1,
				'description' => '白诘草神社的主持，祭神实验计划的主要推手之一。',
			),
			3 => array
			(
				'count' => 1,
				'description' => '代号【无聊】，真名不详。克隆士兵实验计划的队长兼克隆原型体。没有捂脸以及萝莉就完全不行的家伙。',
			),
		),
	),
	13 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '凉亭区的管理员少女。软软的没什么战斗力的样子，但是惹她生气就不太好了。',
				//'description' => '凉亭区的管理员少女,软软的。似乎受到节日气氛的感染有点过于兴奋。小心一点不要被卷进去了。',
			),
		),
	),
	14 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '哎呀手滑了拿了武器。',
			),
			1 => array
			(
				'count' => 1,
				'description' => '这次一定会Hack成功！',
			),
		),
	),
	40 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '无辜的医生。',
			),
			1 => array
			(
				'count' => 1,
				'description' => '无辜的护士。',
			),
		),
	),
	41 => array
	(
		'count' => 12,
		'description' => '白诘草神社所属的巫女们。普通程度的战斗力。',
		'sub' => array
		(
			0 => array(),
			1 => array(),
			2 => array(),
			3 => array(),
			4 => array(),
		),
	),
	42 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '……',
			),
		),
	),
	12 => array
	(
		'description' => '随处可见的深渊之民。不需要刻意去认识他/她。',
		'count' => 1,
		'sub' => array
		(
			0 => array(),
			1 => array(),
			2 => array(),
			3 => array(),
			4 => array(),
			5 => array(),
			6 => array(),
			7 => array(),
			8 => array(),
			9 => array(),
			10 => array(),
			11 => array(),
			12 => array(),
			13 => array(),
			14 => array(),
			15 => array(),
			16 => array(),
			17 => array(),
			18 => array(),
			19 => array(),
			20 => array(),
			21 => array(),
			22 => array(),
			23 => array(),
			24 => array(
			'description' => '屡次乱修改，问题很大的深渊之民。',
			),
			25 => array(),
			26 => array(),
			27 => array(),
		),
	),
	17 => array
	(
		'count' => 1,
		'description' => '缠绕着不详气息的深渊灾厄。',
		'sub' => array
		(
			0 => array(),
			1 => array(),
			2 => array(),
			3 => array(),
			4 => array(),
			5 => array(),
			6 => array(),
		),
	),
/*	5 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '杏仁豆腐 冴月 麟，对玩家有较大威胁，掉落启动死斗模式的钥匙，和很强力的灵系武器。',
			),
			1 => array
			(
				'count' => 1,
				'description' => '杏仁豆腐 某四面，对玩家有较大威胁，掉落启动死斗模式的钥匙，和很强力的射系武器。',
			),
		),
	),*/
/*	6 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '黑幕 Acg_Xilin，对玩家具有很大威胁，如果防御值没有达到2000最好不要惹他（她）。掉落可以杀死任意一名玩家的道具“死亡笔记”，和大量的金钱。',
			),
		),
	),
	9 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '感觉像蓝凝的东西，好像被某种病毒感染了，看上去比较奇怪。<span class="yellow">没事还是不要惹她好了……</span>',
			),
		),
	),
	11 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '真职人 Hank，使用带有全属性的爆系武器，掉落极优秀的防具。',
			),
			1 => array
			(
				'count' => 1,
				'description' => '真职人 爱情上甘岭，使用带有全属性的斩系武器，掉落极优秀的防具。',
			),
			2 => array
			(
				'count' => 1,
				'description' => '真职人 221，使用带有全属性的殴系武器，掉落极优秀的防具。',
			),
			3 => array
			(
				'count' => 1,
				'description' => '真职人 Erul Tron，使用带有全属性的射系武器，掉落极优秀的防具。',
			),
			4 => array
			(
				'count' => 1,
				'description' => '真职人 亚玛丽欧·维拉蒂安，使用带有全属性的殴系武器，掉落极优秀的防具。',
			),
			5 => array
			(
				'count' => 1,
				'description' => '真职人 比利·海灵顿，使用带有全属性的重型枪械，掉落极优秀的防具。',
			),
			6 => array
			(
				'count' => 1,
				'description' => '真职人 便当盒，ACFUN大逃杀吉祥物，卖萌的存在，拥有888万点HP和双抹消饰品，几乎无法杀死。',
			),
			7 => array
			(
				'count' => 1,
				'description' => '真职人 別忘了我，ACFUN大逃杀吉祥物，新人导师一般的存在，拥有888万点HP和双抹消饰品，几乎无法杀死。',
			),
		),
	),
	14 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '数据碎片 讲解员 梦美，<span class="yellow">被击杀后会变身为攻击力极强的NPC</span>。',
			),
			1 => array
			(
				'count' => 1,
				'description' => '数据碎片 喧哗少女 叶留佳，<span class="yellow">被击杀后会变身为攻击力极强的NPC</span>。',
			),
			2 => array
			(
				'count' => 1,
				'description' => '数据碎片 风纪委员 静流，<span class="yellow">被击杀后会变身为攻击力极强的NPC</span>。',
			),
		),
	),*/
	/*24 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '游动萌物 测试用鱼装自走兵器，看起来像鱼一样的东西，拥有报社程度的能力。<span class="yellow">攻击带有【击毁装备/击毁道具/按照金钱数量计算伤害/按照经验计算伤害/毒雾/增加生命上限和金钱】六种效果中随机一种</span>。',
			),
		),
	),*/
/*	21 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '武神 虚子，<span class="yellow">旧英灵四天王之首，被称为英灵殿唯一的良心。（咦？）</span><br><span class="red">刷新虚子时随机选择一个副本。</span>',
			),
			1 => array
			(
				'count' => 1,
				'description' => '武神 虚子，<span class="yellow">旧英灵四天王之首，被称为英灵殿唯一的良心。（咦？）</span><br><span class="red">虚子分裂是由于电波与时空节点融合后扭曲虚空的幻象所造成的。</span>',
			),
			2 => array
			(
				'count' => 1,
				'description' => '武神 水月，<span class="yellow">旧英灵四天王之一。</span>身上的火金符对玩家威胁很大，称号为换装迷宫，台词来源于圣经。初始武器自带双抹，但威力不足。',
			),
			3 => array
			(
				'count' => 1,
				'description' => '武神 黑色奪魂曲，<span class="yellow">英灵殿吉祥物。</span>攻击力低，二形态血量为1000W，自带双抹，同时武器拥有贯穿属性，具有一定威胁。',
			),	
			4 => array
			(
				'count' => 1,
				'description' => '武神 北京推倒你，<span class="yellow">曾经被誉为最弱武神，经过BUFF后变的丧心病狂起来。</span>武器为空手，但拥有6000点的基础熟练，隐隐有成为小黑熊的架势。',
			),
			5 => array
			(
				'count' => 1,
				'description' => '武神 BorisX，<span class="yellow">旧英灵四天王之一，经过BUFF后变的更加丧心病狂。</span>武器为重枪，同时具有1150点的基础熟练，而且血量也有所提升，大家看见之后绕着走就行了。',
			),
			6 => array
			(
				'count' => 1,
				'description' => '武神 Renamon，<span class="yellow">旧时代毫无存在感的武神之一，被BUFF能拯救她阿卡林的命运吗？</span>血量为武神中最高，同时武器基础效和全熟在被BUFF后隐隐有与当年黄鸡寻星比肩的势头。',
            ),
			7 => array
			(
				'count' => 1,
				'description' => '武神 beijuzhu，<span class="yellow">旧时代毫无存在感的武神之一，被BUFF能拯救他阿卡林的命运吗？</span>虽然和小狐一样，武器基础效得到了BUFF，但看起来还是很弱小。',
            ),
			8 => array
			(
				'count' => 1,
				'description' => '武神 捂脸姬，<span class="yellow">旧时代毫无存在感的武神之一，被BUFF能拯救她阿卡林的命运吗？</span>少数没有强袭姿态的武神之一，但是武器基础效直接被提高了十倍，看起来很危险的样子。',
            ),
			9 => array
			(
				'count' => 1,
				'description' => '武神 Yoshiko-G，<span class="yellow">四面衍生物，特征是毒舌与傲娇。</span>武神中基础防御力仅低于lemon，在得到BUFF后翻身农奴把歌唱，自带迅疾和静息技能，同时称号变为天赋，要被耀西子教做人了吗！？',
            ),
			10 => array
			(
				'count' => 1,
				'description' => '武神 lemon，<span class="yellow">旧英灵四天王之一，经过BUFF后，好像没啥影响。</span><span class="yellow">拥有最高的基础攻击与防御，十分吓人，当然现在比起来好像也不是那么吓人了。</span>经过BUFF之后火绳枪被改成了重枪，不过好像不如以前了喂！？',
			),
			11 => array
			(
				'count' => 1,
				'description' => '武神 埃尔兰卡，<span class="yellow">新晋武神，看起来弱的不行，这家伙真的是武神吗？</span>武神中无论是攻击、防御还是血量都是最低的一位，但是其武器却带有许多这里写不下的特殊效果。<span class="yellow">掉落的盒子与里海之誓都有特殊的效果！</span>',
            ),
		),
	),
	22 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '天神 冴月麟MK-II，ACFUN大逃杀的创作者。KEY社的铁杆粉丝。会切换武器。（没有键 催泪弹是刻意的）',
			),
			1 => array
			(
				'count' => 1,
				'description' => '天神 星莲船四面BOSS，AC大逃杀程序员、抖M。虽然武器的攻击力不高，但由于重型枪械的百分比伤害设定，实际上对玩家拥有即死效果。',
			),
		),
	),
	*/
	25 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '肥宅，随处可见的肥胖宅男。没有任何威胁。',
			),
			1 => array
			(
				'count' => 1,
				'description' => '春原 阳平，马桶盖子专家。',
			),
			2 => array
			(
				'count' => 1,
				'description' => '真猎人，只玩破解中文版怪物猎人的真玩家。',
			),	
			3 => array
			(
				'count' => 1,
				'description' => '彩虹独角兽，在宅男中拥有很高人气的小动物。会使用神奇的魔法。',
			),
			4 => array
			(
				'count' => 1,
				'description' => '海星王，沉迷卡牌游戏的洗剪吹不良少年。有精神分裂症。',
			),
			5 => array
			(
				'count' => 1,
				'description' => '红帽少年，周游日本开后宫的年轻动物学家。',
            ),
			6 => array
			(
				'count' => 1,
				'description' => '海豹部队，希望国维护世界和平的重要力量。<span class="yellow">当心他的怒气技能！</span>',
            ),
			7 => array
			(
				'count' => 1,
				'description' => '圣德太子，带着奇怪耳机的偏执狂。必杀是飞鸟文化无力回天。',
            ),
			8 => array
			(
				'count' => 1,
				'description' => 'FV4202，性能中庸地位尴尬的中型坦克。',
            ),
			9 => array
			(
				'count' => 1,
				'description' => '萨鲁法尔大王，部落的英雄，联盟的噩梦。',
			),
			10 => array
			(
				'count' => 1,
				'description' => 'Chuck Norris，美国第一硬汉。其地位与春哥在中国的地位相似。',
			),
		),
	),
	/*
	30 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '代码聚合体 霜火协奏曲，大逃杀史上最大的触手。<span class="yellow">特定种类以外的武器对他是无效的。</span>',
			),
			1 => array
			(
				'count' => 1,
				'description' => '代码聚合体 tabris，远古巨触，霜火一生的对手。<span class="yellow">伤害他只会让他变的更强。</span>',
			),
			2 => array
			(
				'count' => 1,
				'description' => '代码聚合体 菜包，大逃杀第一脸骑士，同时拥有卓绝的手速和意识。<span class="yellow">随身携带了无数的阔剑地雷。</span>',
			),
			3 => array
			(
				'count' => 1,
				'description' => '代码聚合体 一旦接受这种设定，大逃杀史上最强的脚本党，脱离脚本也拥有惊人的战斗力。<span class="yellow">对他来说一瞬千击也并不是不可能达成的。</span>',
			),
		),
	),
	31 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '代码聚合体 院长，巨触+各种意义上的人生赢家。<span class="yellow">小心别被晒瞎了。</span>',
			),
			1 => array
			(
				'count' => 1,
				'description' => '代码聚合体 飞雪大大，飞雪大魔王，沙包们最好的朋友。和院长连年大战不分胜负。<span class="yellow">同样的武器对大魔王不能使用两次。</span>',
			),
			2 => array
			(
				'count' => 1,
				'description' => '代码聚合体 左手，ACFUN著名页游玩家，ACFUN著名炉石玩家。<span class="yellow">经历了大逃杀无数年代的左手早已看穿了一切攻击。</span>',
			),
		),
	),
	32 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => '代码聚合体 别忘了我，指导了无数新人，陪同了无数次的PVE。<span class="yellow">几乎无敌的存在。</span>',
			),
			1 => array
			(
				'count' => 1,
				'description' => '代码聚合体 冰冻青蛙，篝火服和时空服的提供者，做了很多设计和构建大逃杀世界的工作。<span class="yellow">咸鱼的目标从来不是杀死玩家。</span>',
			),
			2 => array
			(
				'count' => 1,
				'description' => '代码聚合体 sillycross，ACFUN大逃杀程序员，代码神犇，编写了AI、成就、团战/SOLO、技能点等一系列功能。<span class="yellow">几乎无敌的存在。</span>',
			),
		),
	),
	45 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 2,
				'description' => '电波幽灵 索菲亚小傻鸟，电波第一代触手代表。另一个身份是A岛美食版女神kitty酱。',
			),
			1 => array
			(
				'count' => 2,
				'description' => '电波幽灵 虚名，电波第二代触手代表。本命武器为精灵片翼。',
			),
			2 => array
			(
				'count' => 2,
				'description' => '电波幽灵 YS，电波第三代触手代表。是一名脸很黑的小学生。',
			),
			3 => array
			(
				'count' => 2,
				'description' => '电波幽灵 逆向朝阳，电波第二代触手，电波前段时间的统治者。养了很多猫大爷。',
			),
		),
	),
	88 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 1,
				'description' => 'SCP-682，坐镇于SCP研究设施，完全无敌的存在，要是不幸被打到的话，必死无疑。最好的避免方法，就是<span class="yellow">永远不要去SCP研究设施</span>。',
			),
			1 => array
			(
				'count' => 1,
				'description' => 'SCP-173，坐镇于SCP研究设施，完全无敌的存在，要是不幸被打到的话，必死无疑。最好的避免方法，就是<span class="yellow">永远不要去SCP研究设施</span>。',
			),
			2 => array
			(
				'count' => 1,
				'description' => 'SCP-076，坐镇于SCP研究设施，完全无敌的存在，要是不幸被打到的话，必死无疑。最好的避免方法，就是<span class="yellow">永远不要去SCP研究设施</span>。',
			),
			3 => array
			(
				'count' => 1,
				'description' => 'SCP-958，坐镇于SCP研究设施，完全无敌的存在，要是不幸被打到的话，必死无疑。最好的避免方法，就是<span class="yellow">永远不要去SCP研究设施</span>。',
			),
		),
	),*/
	90 => array
	(
		'sub' => array
		(
			0 => array
			(
				'count' => 80,
				'description' => '无威胁的小兵，也是数目最多的NPC。以无聊为原型的克隆实验的产品，碰见了就上去给他一击吧。',
			),
			1 => array
			(
				'count' => 80,
				'description' => '无威胁的小兵，也是数目最多的NPC。以无聊为原型的克隆实验的产品，碰见了就上去给他一击吧。',
			),
			2 => array
			(
				'count' => 80,
				'description' => '无威胁的小兵，也是数目最多的NPC。以无聊为原型的克隆实验的产品，碰见了就上去给他一击吧。',
			),
		),
	),
);

?>
