--
-- 表的结构 `bra_players`
-- 储存角色数据的激活信息，包括PC和NPC。
--

DROP TABLE IF EXISTS bra_players;
CREATE TABLE bra_players (
  pid smallint unsigned NOT NULL auto_increment,
  type tinyint NOT NULL default '0',
  name char(15) NOT NULL default '',
  pass char(32) NOT NULL default '',
  gd char(1) NOT NULL default 'm',
  sNo smallint unsigned NOT NULL default '0',
  icon smallint unsigned NOT NULL default '0',
  club tinyint unsigned NOT NULL default '0',
  endtime int(10) unsigned NOT NULL default '0',
  validtime int(10) unsigned NOT NULL default '0',
  deathtime int(10) unsigned NOT NULL default '0',
  cmdnum int unsigned NOT NULL default '0',
  achievement text NOT NULL default '',
  nick text NOT NULL default '',
  nicks text NOT NULL default '',
  skillpoint smallint unsigned NOT NULL default '0',
  skills mediumint unsigned NOT NULL default '0',
  cdsec int(10) unsigned NOT NULL default '0',
  cdmsec smallint(3) unsigned NOT NULL default '0',
  cdtime mediumint unsigned NOT NULL default '0',
  action char(12) NOT NULL default '',
  hp int unsigned NOT NULL default '0',
  mhp int unsigned NOT NULL default '0',
  sp smallint unsigned NOT NULL default '0',
  msp smallint unsigned NOT NULL default '0',
  ss smallint unsigned NOT NULL default '0',
  mss smallint unsigned NOT NULL default '0',
  wepexp int unsigned NOT NULL default '0',
  att int unsigned NOT NULL default '0',
  def int unsigned NOT NULL default '0',
  pls tinyint unsigned NOT NULL default '0',
  lvl tinyint unsigned NOT NULL default '0',
  `exp` smallint unsigned NOT NULL default '0',
  money mediumint unsigned NOT NULL default '0',
  rp mediumint unsigned NOT NULL default '0',
  bid smallint unsigned NOT NULL default '0',
  `inf` char(10) not null default '',
  rage tinyint unsigned NOT NULL default '0',
  sktime int unsigned NOT NULL default '0',
  pose tinyint(1) unsigned NOT NULL default '0',
  tactic tinyint(1) unsigned NOT NULL default '0',
  killnum smallint unsigned NOT NULL default '0',
  state tinyint unsigned NOT NULL default '0',
  `wp` smallint unsigned not null default '0',
  `wk` smallint unsigned not null default '0',
  `wg` smallint unsigned not null default '0',
  `wc` smallint unsigned not null default '0',
  `wd` smallint unsigned not null default '0',
  `wf` smallint unsigned not null default '0',
  `teamID` char(15) not null default '',
  `teamPass` char(15) not null default '',
  getitem text NOT NULL default '',
  itembag text NOT NULL default '',
  itmnum smallint unsigned NOT NULL default '0',
  itmnumlimit smallint unsigned NOT NULL default '0',
  wep varchar(40) NOT NULL default '',
  wepk char(10) not null default '',
  wepe int unsigned NOT NULL default '0',
  weps char(5) not null default '0',
  wepsk varchar(25) not null default '',
  arb varchar(40) NOT NULL default '',
  arbk char(5) not null default '',
  arbe int unsigned NOT NULL default '0',
  arbs char(5) not null default '0',
  arbsk varchar(25) not null default '',
  arh varchar(40) NOT NULL default '',
  arhk char(5) not null default '',
  arhe int unsigned NOT NULL default '0',
  arhs char(5) not null default '0',
  arhsk varchar(25) not null default '',
  ara varchar(40) NOT NULL default '',
  arak char(5) not null default '',
  arae int unsigned NOT NULL default '0',
  aras char(5) not null default '0',
  arask varchar(25) not null default '',
  arf varchar(40) NOT NULL default '',
  arfk char(5) not null default '',
  arfe int unsigned NOT NULL default '0',
  arfs char(5) not null default '0',
  arfsk varchar(25) not null default '',
  art varchar(40) NOT NULL default '',
  artk char(5) not null default '',
  arte int unsigned NOT NULL default '0',
  arts char(5) not null default '0',
  artsk varchar(25) not null default '',
  itm0 varchar(40) NOT NULL default '',
  itmk0 char(10) not null default '',
  itme0 int unsigned NOT NULL default '0',
  itms0 char(5) not null default '0',
  itmsk0 varchar(25) not null default '',
  itm1 varchar(40) NOT NULL default '',
  itmk1 char(10) not null default '',
  itme1 int unsigned NOT NULL default '0',
  itms1 char(5) not null default '0',
  itmsk1 varchar(25) not null default '',
  itm2 varchar(40) NOT NULL default '',
  itmk2 char(10) not null default '',
  itme2 int unsigned NOT NULL default '0',
  itms2 char(5) not null default '0',
  itmsk2 varchar(25) not null default '',
  itm3 varchar(40) NOT NULL default '',
  itmk3 char(10) not null default '',
  itme3 int unsigned NOT NULL default '0',
  itms3 char(5) not null default '0',
  itmsk3 varchar(25) not null default '',
  itm4 varchar(40) NOT NULL default '',
  itmk4 char(10) not null default '',
  itme4 int unsigned NOT NULL default '0',
  itms4 char(5) not null default '0',
  itmsk4 varchar(25) not null default '',
  itm5 varchar(40) NOT NULL default '',
  itmk5 char(10) not null default '',
  itme5 int unsigned NOT NULL default '0',
  itms5 char(5) not null default '0',
  itmsk5 varchar(25) not null default '',
  itm6 varchar(40) NOT NULL default '',
  itmk6 char(10) not null default '',
  itme6 int unsigned NOT NULL default '0',
  itms6 char(5) not null default '0',
  itmsk6 varchar(25) not null default '',
  flare int(10) NOT NULL default '0',
  dcloak int(10) NOT NULL default '0',
  auraa int(10) NOT NULL default '0',
  aurab int(10) NOT NULL default '0',
  aurac int(10) NOT NULL default '0',
  aurad int(10) NOT NULL default '0',
  aurae int(10) NOT NULL default '0',
  souls int(10) NOT NULL default '0',
  debuffa int(10) NOT NULL default '0',
  debuffb int(10) NOT NULL default '0',
  debuffc int(10) NOT NULL default '0',
  vcode char(1) not null default '',
  gemstate tinyint(3) unsigned NOT NULL DEFAULT '0',
  gemname char(30) NOT NULL default '',
  gempower char(5) not null default '0',
  gemexp smallint unsigned NOT NULL default '0',
  gemlvl tinyint unsigned NOT NULL default '0',
  typls tinyint unsigned NOT NULL default '0',
  tyowner varchar(30) NOT NULL default '',
  PRIMARY KEY  (pid),
  INDEX TYPE (type, sNo),
  INDEX NAME (name, type)
	
) ENGINE=MyISAM;



